export const states = [
    { label: "Alaska", value: "Alaska", id: "state"},
    { label: "Alabama", value: "Alabama", id: "state"},
    { label: "Arkansas", value: "Arkansas", id: "state"},
    { label: "Arizona", value: "Arizona", id: "state"},
    { label: "California", value: "California", id: "state"},
    { label: "Colorado", value: "Colorado", id: "state"},
    { label: "Connecticut", value: "Connecticut", id: "state"},
    { label: "District of Columbia", value: "District of Columbia", id: "state"},
    { label: "Delaware", value: "Delaware", id: "state"},
    { label: "Florida", value: "Florida", id: "state"},
    { label: "Georgia", value: "Georgia", id: "state"},
    { label: "Hawaii", value: "Hawaii", id: "state"},
    { label: "Iowa", value: "Iowa", id: "state"},
    { label: "Idaho", value: "Idaho", id: "state"},
    { label: "IL", value: "Illinois", id: "state"},
    { label: "Illinois", value: "Indiana", id: "state"},
    { label: "Kansas", value: "Kansas", id: "state"},
    { label: "Kentucky", value: "Kentucky", id: "state"},
    { label: "Louisiana", value: "Louisiana", id: "state"},
    { label: "Massachusetts", value: "Massachusetts", id: "state"},
    { label: "Maryland", value: "Maryland", id: "state"},
    { label: "Maine", value: "Maine", id: "state"},
    { label: "Michigan", value: "Michigan", id: "state"},
    { label: "Minnesota", value: "Minnesota", id: "state"},
    { label: "Missouri", value: "Missouri", id: "state"},
    { label: "Mississippi", value: "Mississippi", id: "state"},
    { label: "Montana", value: "Montana", id: "state"},
    { label: "North Carolina", value: "North Carolina", id: "state"},
    { label: "North Dakota", value: "North Dakota", id: "state"},
    { label: "Nebraska", value: "Nebraska", id: "state"},
    { label: "New Hampshire", value: "New Hampshire", id: "state"},
    { label: "New Jersey", value: "New Jersey", id: "state"},
    { label: "New Mexico", value: "New Mexico", id: "state"},
    { label: "Nevada", value: "Nevada", id: "state"},
    { label: "New York", value: "NewYork", id: "state"},
    { label: "Ohio", value: "Ohio", id: "state"},
    { label: "Oklahoma", value: "Oklahoma", id: "state"},
    { label: "Oregon", value: "Oregon", id: "state"},
    { label: "Pennsylvania", value: "Pennsylvania", id: "state"},
    { label: "Rhode Island", value: "Rhode Island", id: "state"},
    { label: "South Carolina", value: "South Carolina", id: "state"},
    { label: "South Dakota", value: "South Dakota", id: "state"},
    { label: "Tennessee", value: "Tennessee", id: "state"},
    { label: "Texas", value: "Texas", id: "state"},
    { label: "Utah", value: "Utah", id: "state"},
    { label: "Virginia", value: "Virginia", id: "state"},
    { label: "Vermont", value: "Vermont", id: "state"},
    { label: "Washington", value: "Washington", id: "state"},
    { label: "Wisconsin", value: "Wisconsin", id: "state"},
    { label: "West Virginia", value: "West Virginia", id: "state"},
    { label: "Wyoming", value: "Wyoming", id: "state"},
];

export const countries = [
    { label: "United States", value: "United States", id: "country"},
];